templates:
- '/etc/alertmanager/template/*.tmpl'

global:
route:
  receiver: 'ops-defualt-receiver'
  group_by: [app, group, env]
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

  routes:
    - receiver: 'ops-prod-where-is-my-money-api'
      match:
        system: 'prod-where-is-my-money-api'

receivers:
- name: ops-defualt-receiver
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#default-channel'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.app }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Summary:* {{ .Annotations.summary }}
     
     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}

- name: 'ops-prod-where-is-my-money-api'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#prod-where-is-my-money-api'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.app }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Summary:* {{ .Annotations.summary }}
     
     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}
