version: "3.8"
services:
  prod-where-is-my-money-api:
    image: augustomarques/where-is-my-money-api:latest
    container_name: prod-where-is-my-money-api
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: 10.11.12.20
      DB_PORT: 5454
      DB_DATABASE: where-is-my-money
      DB_USERNAME: user-where-is-my-money
      DB_PASSWORD: password-where-is-my-money
      ACCESS_TOKEN_SECRET_KEY: 2ae53b07a3cb4277e179d99635c144960e2fab8c
      ACCESS_TOKEN_EXPIRATION: 86400000
      REFRESH_TOKEN_SECRET_KEY: b3ffe798925c47e0afd8f4c0815259939ea19697
      REFRESH_TOKEN_EXPIRATION: 604800000
    ports:
      - "18080:8080"
    networks:
      - prod-where-is-my-money-network
  
  prod-where-is-my-money-frontend:
    image: augustomarques/where-is-my-money-frontend:latest
    container_name: prod-where-is-my-money-frontend
    restart: unless-stopped
    ports:
      - "1080:80"
    depends_on:
      - prod-where-is-my-money-api

networks:
  prod-where-is-my-money-network:
    name: prod-development
    external: true
