version: "3.8"
services:
  prod-where-is-my-money-api:
    image: augustomarques/where-is-my-money-api
    container_name: prod-where-is-my-money-api
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: 10.11.12.20
      DB_PORT: 5454
      DB_DATABASE: where-is-my-money
      DB_USERNAME: user-where-is-my-money
      DB_PASSWORD: password-where-is-my-money
    ports:
      - "18080:8080"
    networks:
      - prod-where-is-my-money-network
  
  prod-where-is-my-money-frontend:
    image: augustomarques/where-is-my-money-frontend
    container_name: prod-where-is-my-money-frontend
    restart: unless-stopped
    ports:
      - "10080:80"
    depends_on:
      - prod-where-is-my-money-api

networks:
  prod-where-is-my-money-network:
    name: prod-development
    external: true
