datasources:
  - name: Prometheus
    access: proxy
    type: prometheus
    url: http://prod-prometheus:19090
    isDefault: true
  - name: Loki
    access: proxy
    type: loki
    orgId: 1
    url: http://prod-loki:13100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
